# How long (in minutes) the server has to be empty before pausing.
idleTimeout: 5

# What should be paused when the server is inactive:
pauseWeather: true  # Stops weather changes
pauseDaylight: true # Stops day/night progression.